# ---- Stage 1: Build ----
FROM eclipse-temurin:17-jdk AS build
WORKDIR /app

# Copy gradle wrapper first
COPY gradlew .
COPY gradle ./gradle
COPY build.gradle.kts settings.gradle.kts gradle.properties ./

# Give execution permission and fetch dependencies
RUN chmod +x gradlew && ./gradlew dependencies --no-daemon || true

COPY src ./src
RUN ./gradlew installDist --no-daemon

# ---- Stage 2: Runtime ----
FROM eclipse-temurin:17-jre
WORKDIR /app

# The build/install folder name usually matches the project name in settings.gradle.kts
COPY --from=build /app/build/install/literature-search-bot ./

# Create non-root user
RUN useradd -ms /bin/bash botuser && chown -R botuser:botuser /app
USER botuser

# Using the full path to the script generated by installDist
ENTRYPOINT ["./bin/literature-search-bot"]